import { NextResponse } from 'next/server';
import prisma from '@/lib/prisma';

export async function POST() {
  try {
    // Eski verileri temizle ki çakışma yaşanmasın
    await prisma.service.deleteMany();

    const staticServices = [
    {
        "title": "Arama Motoru Optimizasyonu",
        "slug": "arama-motoru-optimizasyonu",
        "miniDescription": "Web siteniz için, hedef kitlenizin markanızı arama motorlarında daha kolay bulması için performans odaklı anahtar kelime stratejisi sunuyoruz.",
        "iconPath": "/seo1.png",
        "isFeaturedHome": true,
        "detailMainTitle": "Doğru İçerik, Optimizasyon, Verimlilik.",
        "detailSmallDescription": "Web siteniz için, hedef kitlenizin markanızı arama motorlarında daha kolay bulması için performans odaklı anahtar kelime stratejisi sunuyoruz.",
        "image1": "/seo1.png",
        "subTitle1": "Organik Olarak Artan Satış Verimliliği",
        "text1": "Web siteniz için, hedef kitlenizin markanızı veya ürününüzü arama motorlarında daha kolay bulması için performans odaklı anahtar kelime stratejisi ve içerik optimizasyonu sağlarız.",
        "image2": "/seo2.png",
        "subTitle2": "Organik Olarak Artan Satış Verimliliği",
        "text2": "Markanız için organik olarak artan satış, artan kârlılık ve azalan maliyet verimliliği inşa ederiz. Kalıcı başarı için SEO stratejilerini markanızın hedefleri doğrultusunda şekillendiriyoruz.",
        "image3": "/seo3.png",
        "subTitle3": "Sürdürülebilir Dijital Başarı",
        "text3": "Neo Brand Digital olarak uzman SEO ekibimizle markanızın dijital varlığını sürdürülebilir bir büyüme ivmesine geçiriyoruz.",
        "order": 1
    },
    {
        "title": "Dijital Strateji Yönetimi",
        "slug": "dijital-strateji-yonetimi",
        "miniDescription": "Neo Brand Digital olarak dijital strateji yönetimiyle markanızın, kullanıcı kitlesiyle en verimli şekilde etkileşime geçmesi için çalışıyoruz.",
        "iconPath": "/dijital1.png",
        "isFeaturedHome": true,
        "detailMainTitle": "Hayal Et, Hedef Belirle, Gerçekleştir.",
        "detailSmallDescription": "Neo Brand Digital olarak dijital strateji yönetimiyle markanızın, kullanıcı kitlesiyle en verimli şekilde etkileşime geçmesi için çalışıyoruz.",
        "image1": "/dijital1.png",
        "subTitle1": "Strateji Doğru Adımlarla Başlar.",
        "text1": "Neo Brand Digital olarak dijital strateji yönetimiyle markanızın, kullanıcı kitlesiyle en verimli şekilde etkileşime geçmesi için çalışıyoruz.",
        "image2": "/dijital2.png",
        "subTitle2": "Strateji Doğru Adımlarla Başlar.",
        "text2": "Hedef kitlenizi potansiyel müşterilerinize dönüştürmek için, dijital mecralarda ihtiyaçlarınıza yönelik öneriler sunar, etkili çözümlerle markanızı doğru zamanda doğru yerde konumlandırırız.",
        "image3": "/dijital3.png",
        "subTitle3": "Strateji ve Hedeflerin Güncellenmesi Gerekebilir.",
        "text3": "Artık markaların dijital dünyada da bir yol göstericiye ihtiyaçları var...",
        "order": 2
    },
    {
        "title": "Eticaret Danışmanlığı",
        "slug": "e-ticaret-danismanligi",
        "miniDescription": "Eticaret mağazanız istediğiniz performansı göstermiyor mu? Eticaret danışmanlık hizmetimizle tüm süreçlerinize birlikte göz atalım.",
        "iconPath": "/dijital1.png",
        "isFeaturedHome": true,
        "detailMainTitle": "Dijital Mağazanızın Gerçek Potansiyelini Keşfedin",
        "detailSmallDescription": "Eticaret mağazanız istediğiniz performansı göstermiyor mu? Eticaret danışmanlık hizmetimizle tüm süreçlerinize birlikte göz atalım.",
        "image1": "/dijital1.png",
        "subTitle1": "Satış ve Dönüşüm Optimizasyonu",
        "text1": "Bir e-ticaret sitesi kurmak başarının sadece ilk adımıdır. Trafiğinizi satışa döndürmek, sepet terk etme oranlarını düşürmek ve karlılığı artırmak için veriye dayalı stratejilere ihtiyacınız var.",
        "image2": "/dijital2.png",
        "subTitle2": "Kullanıcı Yolculuğunu Pürüzsüzleştirin",
        "text2": "Ziyaretçilerinizin sitenize girdiği andan ödeme sayfasına kadar olan yolculuğunu analiz ediyor, tıkanıklık yaratan noktaları ortadan kaldırıyoruz. Hızlı ödeme adımları ve SEO uyumlu ürün sayfalarıyla satış hacminizi organik olarak büyütüyoruz.",
        "image3": "/dijital3.png",
        "subTitle3": "Uçtan Uca Pazar Yeri Yönetimi",
        "text3": "Sadece kendi web sitenizde değil, pazar yerlerinde de markanızı doğru konumlandırıyoruz. Fiyatlandırma, stok entegrasyonu ve kampanya yönetimiyle 360 derece e-ticaret süreçlerinize liderlik ediyoruz.",
        "order": 3
    },
    {
        "title": "Eposta Pazarlama",
        "slug": "eposta-pazarlama",
        "miniDescription": "Liste oluşturma, mailing tasarımı ve içerik üretimi ve pazarlama otomasyonu! Birlikte planlamaya hazırız.",
        "iconPath": "/dijital1.png",
        "isFeaturedHome": true,
        "detailMainTitle": "Müşterilerinizin Kutusunda Değil, Aklında Yer Edinin",
        "detailSmallDescription": "Liste oluşturma, mailing tasarımı ve içerik üretimi ve pazarlama otomasyonu! Birlikte planlamaya hazırız.",
        "image1": "/dijital1.png",
        "subTitle1": "Akıllı Otomasyon Kurguları",
        "text1": "E-posta pazarlama, doğru kullanıldığında yatırım getirisi (ROI) en yüksek dijital pazarlama kanallarından biridir. Sadece e-posta göndermekle kalmıyor, hedef kitlenizle bağ kuran, kişiselleştirilmiş bültenler hazırlıyoruz.",
        "image2": "/dijital2.png",
        "subTitle2": "Sepette Kalanları Kazanca Dönüştürün",
        "text2": "Müşterilerinize doğru zamanda doğru mesajı iletmek için e-posta otomasyon sistemleri kuruyoruz. Hoş geldin serileri, sepet terk etme hatırlatmaları ve özel gün indirimleriyle dönüşüm oranlarınızı katlıyoruz.",
        "image3": "/dijital3.png",
        "subTitle3": "Yüksek Açılma ve Tıklanma Oranları",
        "text3": "Spam kutusuna düşmeyen, merak uyandıran konu başlıkları ve tıklamaya teşvik eden içeriklerle mailing kampanyalarınızı optimize ediyor, her gönderimde raporlarla başarıyı kanıtlıyoruz.",
        "order": 4
    },
    {
        "title": "Grafik ve Video Tasarım",
        "slug": "grafik-ve-video-tasarim",
        "miniDescription": "Hedef kitlenize ulaşmak, ürün ve hizmetlerinizi bir adım daha öne çıkarmak için yaratıcı tasarım ve sloganları hazırlar; bu tasarımları web, mobil ve diğer tüm cihazlar için uyumlu hale getiririz.",
        "iconPath": "/grafik1.png",
        "isFeaturedHome": true,
        "detailMainTitle": "Saniyeler İçinde Etkileyin.",
        "detailSmallDescription": "Hedef kitlenize ulaşmak, ürün ve hizmetlerinizi bir adım daha öne çıkarmak için yaratıcı tasarım ve sloganları hazırlar; bu tasarımları web, mobil ve diğer tüm cihazlar için uyumlu hale getiririz.",
        "image1": "/grafik1.png",
        "subTitle1": "Dinamik, Modern ve Akılda Kalıcı",
        "text1": "İlk izlenim her şeydir. Markanızın mesajını uzun cümleler yerine, güçlü ve akılda kalıcı görsellerle anlatıyoruz.",
        "image2": "/grafik2.png",
        "subTitle2": "Harekete Geçiren Görsel İletişim",
        "text2": "Kreatif ekibimiz; estetiği stratejiyle birleştirerek, markanızı rakiplerinden ayıracak eşsiz bir görsel dil inşa eder.",
        "image3": "/grafik3.png",
        "subTitle3": "Hareketin Gücü: Video Prodüksiyon",
        "text3": "İster kurumsal kimlik, ister sosyal medya tasarımı, ister dijital reklam banner'ı... Ürettiğimiz her tasarım, hedef kitleyi harekete geçirmek üzere kurgulanır.",
        "order": 5
    },
    {
        "title": "İçerik Ve Metin Yazarlığı",
        "slug": "icerik-ve-metin-yazarligi",
        "miniDescription": "Web site, blog, ürün açıklamaları ve seo uyumlu özgün yazılan içeriklerde en çok sizin yanınızda olacağız! Organik trafik artışına hazır olun!",
        "iconPath": "/icerik1.png",
        "isFeaturedHome": true,
        "detailMainTitle": "Kelimelerin Gücüyle Zirveye Tırmanın",
        "detailSmallDescription": "Web site, blog, ürün açıklamaları ve seo uyumlu özgün yazılan içeriklerde en çok sizin yanınızda olacağız! Organik trafik artışına hazır olun!",
        "image1": "/icerik1.png",
        "subTitle1": "SEO Uyumlu, Organik ve Çarpıcı",
        "text1": "Arama motorlarında üst sıralara çıkmanın sırrı robotlara değil, insanlara dokunan kaliteli içerikten geçer. Biz, markanızın hikayesini hem Google'ın algoritmalarına hem de hedef kitlenizin kalbine uygun şekilde yazıyoruz.",
        "image2": "/icerik2.png",
        "subTitle2": "Marka Dilinizi Dijitale Taşıyoruz",
        "text2": "Her bir kelimeyi stratejik olarak seçiyor, okunabilirliği yüksek ve organik trafik çekme potansiyeli maksimum metinler üretiyoruz.",
        "image3": "/icerik3.png",
        "subTitle3": "Sadece Okunan Değil, Dönüştüren Kelimeler",
        "text3": "Sıradan, tekrar eden veya sadece anahtar kelime doldurulmuş metinler okuyucuyu sıkar ve sitenizden uzaklaştırır. Biz; blog yazılarından ürün açıklamalarına, web sitesi metinlerinden kategori yazılarına kadar her satırda markanızın kendine özgü sesini yansıtıyoruz.",
        "order": 6
    },
    {
        "title": "Reklam ve Medya Yönetimi",
        "slug": "reklam-ve-medya-yonetimi",
        "miniDescription": "Mevcut ve potansiyel müşterilerinize kolayca ulaşabilmeniz için stratejiler geliştiriyor; dönüşüm değerinizi artıracak reklam modelleriyle birlikte satış oranlarınızı yükseltiyoruz.",
        "iconPath": "/ad1.png",
        "isFeaturedHome": true,
        "detailMainTitle": "Bütçenizi Değil, Etkinizi Büyütün",
        "detailSmallDescription": "Mevcut ve potansiyel müşterilerinize kolayca ulaşabilmeniz için stratejiler geliştiriyor; dönüşüm değerinizi artıracak reklam modelleriyle birlikte satış oranlarınızı yükseltiyoruz.",
        "image1": "/ad1.png",
        "subTitle1": "Doğru Kitle, Doğru Zaman",
        "text1": "Dijital dünyada herkes konuşuyor ama sadece doğru stratejiye sahip olanlar duyuluyor. Sizin için sadece tıklama almıyor, bu tıklamaları doğrudan satışa ve marka sadakatine dönüştürüyoruz.",
        "image2": "/ad2.png",
        "subTitle2": "Veriye Dayalı Dönüşüm Optimizasyonu",
        "text2": "Performans odaklı reklam kampanyalarımızla, bütçenizi en verimli kanallara yönlendiriyor ve yatırım getirinizi (ROI) maksimum seviyeye çıkarıyoruz.",
        "image3": "/ad3.png",
        "subTitle3": "Çok Kanallı Bütünleşik Medya",
        "text3": "Reklam vermek artık sadece bir görsel ve metinden ibaret değil. Gelişmiş piksel takipleri, A/B testleri ve mikro hedeflemeler sayesinde, ürününüzle gerçekten ilgilenen kullanıcıları buluyoruz.",
        "order": 7
    },
    {
        "title": "Sosyal Medya Yönetimi",
        "slug": "sosyal-medya-yonetimi",
        "miniDescription": "Sosyal medyada hedef kitlenize nereden ulaşabileceğinizi en iyi şekilde belirler, etkileşim kurar ve dönüşüm gerçekleştirmenizi sağlarız.",
        "iconPath": "/sosyal1.png",
        "isFeaturedHome": true,
        "detailMainTitle": "Strateji, İçerik, Başarı... Etkili Sosyal Medya Yönetimi.",
        "detailSmallDescription": "Sosyal medyada hedef kitlenize nereden ulaşabileceğinizi en iyi şekilde belirler, etkileşim kurar ve dönüşüm gerçekleştirmenizi sağlarız.",
        "image1": "/sosyal1.png",
        "subTitle1": "Markanızın Hedefi, Bizim Çizeceğimiz Stratejiyi Belirler.",
        "text1": "Sosyal medyada hedef kitlenize nereden ulaşabileceğinizi en iyi şekilde belirler, etkileşim kurar ve dönüşüm gerçekleştirmenizi sağlarız. İçerik takvimlerinizi oluşturur, yaratıcı kampanyalarla hedef kitlenizin sesini duymasını sağlar ve performansla ilgili önemli metrikleri gösteren raporlar hazırlarız.",
        "image2": "/sosyal2.png",
        "subTitle2": "Markanızın Hedefi, Bizim Çizeceğimiz Stratejiyi Belirler.",
        "text2": "Dijital Pazarlama'nın en temel dinamiklerinden olan sosyal medya; hem erişimin gücüyle hem de diğer mecralara oranla düşük bütçe ve hızlı sonuç elde etmesiyle günümüzde markaların kesinlikle varlığını sürdürmesi gereken bir alan...",
        "image3": "/sosyal3.png",
        "subTitle3": "Strateji Oluşturmak İlk İşimiz.",
        "text3": "Neo Brand Digital; bu baş döndüren dijital gelişmeleri takip eden, doğru strateji geliştiren ve uygulayan, markanın hedef kitlesini yakalayan ve o kitleyi hep canlı tutan alanında uzman ekibiyle markanızın sosyal medyadaki gücü için çalışır.",
        "order": 8
    },
    {
        "title": "Strateji Ve Danışmanlık",
        "slug": "strateji-ve-danismanlik",
        "miniDescription": "Kurum içi bir dijital pazarlama ekibiniz var ve desteğe mi ihtiyacınız var? Danışmanlık hizmetimizle yanınızdayız!",
        "iconPath": "/dijital1.png",
        "isFeaturedHome": true,
        "detailMainTitle": "Kurumsal Dijital Zekanızı Güçlendirin",
        "detailSmallDescription": "Kurum içi bir dijital pazarlama ekibiniz var ve desteğe mi ihtiyacınız var? Danışmanlık hizmetimizle yanınızdayız!",
        "image1": "/dijital1.png",
        "subTitle1": "Verimli Süreç Optimizasyonu",
        "text1": "Kendi ekibinizle ilerlemek istiyor ancak dijital dünyadaki hızlı değişimlere yetişmekte zorlanıyorsanız, deneyimlerimizi sizinle paylaşıyoruz. Markanızın büyüme hedeflerine uygun stratejik yol haritaları çiziyoruz.",
        "image2": "/dijital2.png",
        "subTitle2": "Zaman ve Bütçe Tasarrufu",
        "text2": "Pazarlama departmanınızın iş akışlarını analiz ediyor, hangi araçların kullanılacağı ve hangi metriklerin takip edileceği konusunda operasyonel mentörlük sağlıyoruz. Böylece deneme yanılma maliyetlerini ortadan kaldırıyoruz.",
        "image3": "/dijital3.png",
        "subTitle3": "Ekibinize Know-How Desteği",
        "text3": "Veri okuryazarlığı, kampanya analitiği ve dijital trendler konusunda ekibinizi eğitiyor, kapasitelerini artırıyoruz. Siz ana işinize odaklanırken, arka planda markanızın dijital beyni olarak çalışıyoruz.",
        "order": 9
    },
    {
        "title": "Web Tasarım ve Uygulama",
        "slug": "web-tasarim-ve-uygulama",
        "miniDescription": "Neo Brand Digital olarak yapacağımız analizlerle markanızın ihtiyacı olan web sitesini tasarlar, marka kimliğine uygun, UI/UX deneyimiyle birlikte yenilikçi ve modern bir tasarım yaratırız.",
        "iconPath": "/web1.png",
        "isFeaturedHome": true,
        "detailMainTitle": "Dijital Dünyadaki Vitrininiz: Web Siteniz",
        "detailSmallDescription": "Neo Brand Digital olarak yapacağımız analizlerle markanızın ihtiyacı olan web sitesini tasarlar, marka kimliğine uygun, UI/UX deneyimiyle birlikte yenilikçi ve modern bir tasarım yaratırız.",
        "image1": "/web1.png",
        "subTitle1": "Kusursuz UI/UX Tasarım Deneyimi",
        "text1": "Kullanıcıların markanızla dijital dünyada kurduğu ilk temas noktası olan web siteniz, sadece bir adres değil; aynı zamanda kurumsal kimliğinizin ve vizyonunuzun en önemli yansımasıdır. Biz, bu yansımayı en kusursuz haliyle inşa etmek için çalışıyoruz.",
        "image2": "/web2.png",
        "subTitle2": "Hedef Kitleye Uygun Tasarım Mimarisi",
        "text2": "Standart kalıpların ötesine geçerek, markanızın ruhunu yansıtan ve kullanıcı beklentilerini maksimum düzeyde karşılayan, estetik ile teknolojinin harmanlandığı projeler üretiyoruz.",
        "image3": "/web3.png",
        "subTitle3": "Mobil Uyumluluk ve Yüksek Performans",
        "text3": "Başarılı bir web sitesi sadece iyi görünmekle kalmaz, aynı zamanda kullanıcısına pürüzsüz bir gezinme deneyimi sunar. UI (Kullanıcı Arayüzü) ve UX (Kullanıcı Deneyimi) tasarım süreçlerimizde, ziyaretçilerinizin sitenizde kolayca aradığını bulmasını ve dönüşüm hunisinde sorunsuzca ilerlemesini hedefliyoruz.",
        "order": 10
    },
    {
        "title": "Yazılım Geliştirme",
        "slug": "yazilim-gelistirme",
        "miniDescription": "Kurumsal ihtiyaçlarınıza yönelik web ve mobil yazılım çözümlerimizle yanınızdayız!",
        "iconPath": "/dijital1.png",
        "isFeaturedHome": true,
        "detailMainTitle": "Fikirlerinizi Dijital Gerçekliğe Dönüştürüyoruz",
        "detailSmallDescription": "Kurumsal ihtiyaçlarınıza yönelik web ve mobil yazılım çözümlerimizle yanınızdayız!",
        "image1": "/dijital1.png",
        "subTitle1": "Ölçeklenebilir Sistem Mimarisi",
        "text1": "Standart hazır paketler yerine, işletmenizin iş akışına tam uyum sağlayan özel yazılım çözümleri geliştiriyoruz. Hem güvenli hem de yüksek performanslı mimarilerle dijital dönüşümünüze hız katıyoruz.",
        "image2": "/dijital2.png",
        "subTitle2": "Geleceğe Hazır Kodlama Altyapısı",
        "text2": "Projenizi, en yeni teknolojiler ve modern framework'ler kullanarak inşa ediyoruz. Bu sayede uygulamanız sadece bugün değil, artan kullanıcı trafiğiyle gelecekte de sorunsuz çalışacak şekilde ölçeklenebiliyor.",
        "image3": "/dijital3.png",
        "subTitle3": "%100 Mobil ve Platform Uyumluluğu",
        "text3": "Masaüstü, tablet ve mobil cihazlarda aynı mükemmel performansı sunan (cross-platform ve responsive) sistemler geliştiriyoruz. İhtiyacınız olan CRM, ERP veya mobil uygulamaları hızla ve hatasız teslim ediyoruz.",
        "order": 11
    }
];

    await prisma.service.createMany({
      data: staticServices,
    });

    return NextResponse.json({ message: 'Services seeded successfully' }, { status: 201 });
  } catch (error) {
    console.error('Error seeding services:', error);
    return NextResponse.json({ error: 'Failed to seed services' }, { status: 500 });
  }
}
